apiVersion: v1	
kind: Pod	
metadata:
  name: nginx-volume-02		
spec:	
  nodeSelector:	
    kubernetes.io/hostname: server3	
  containers:	
  - name: nginx-test01	
    image: nginx:latest	
    volumeMounts:
    - name: hostpath-test01	
      mountPath: /mount01
  volumes:	
  - name: hostpath-test01	
    hostPath:	
      path: /home/wolf/work/volhost01
      type: DirectoryOrCreate

