apiVersion: v1
kind: PersistentVolume
metadata:
 name: nfs-pv
 labels:
  type: nfs
spec:
 volumeMode: Filesystem
 capacity:
  storage: 3Gi
 accessModes:
  - ReadWriteOnce
 nfs:
  server: 192.168.43.203 
  path: /mnt/shared
