apiVersion: v1	
kind: PersistentVolume	
metadata:
  name: pv-01	
spec:	
  accessModes:	
  - ReadWriteMany
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain	
  storageClassName: pv-test-01	
  nfs:
    server: 192.168.43.203	
    path: /tmp/k8s-pv

